GET http://localhost:4000/api/trainers/ee007900-d9a2-42ee-b165-e0d93e7f488f
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleG1vbiIsImV4cCI6MTY1MDgyNzQ3OSwiaWF0IjoxNjQ4NDA4Mjc5LCJpc3MiOiJleG1vbiIsImp0aSI6IjBmYTQxMjYyLTU0ZjctNDM1ZS05NmJlLTk4NGJhNGNmMjA4NCIsIm5iZiI6MTY0ODQwODI3OCwic3ViIjoiZWUwMDc5MDAtZDlhMi00MmVlLWIxNjUtZTBkOTNlN2Y0ODhmIiwidHlwIjoiYWNjZXNzIn0.dnmWZBeOL08HMn0cGmpGIzI17uH3bFjFwNj0VJpA5ClS9RkjqnQKC0L67zBzrPY51P3FKLk610TM0EOgYbeGjw

###

GET http://localhost:4000/api/pokemons/pikach

###

DELETE http://localhost:4000/api/trainers/816a6a4a-e493-46e6-ae63-041fd8c97404

###
DELETE http://localhost:4000/api/trainer_pokemons/1340831e-54c1-4eb6-8a1f-7cd53050e5ec

###
GET http://localhost:4000/api/trainer_pokemons/11ffc595-fed8-40f4-8cf1-f238edfae5ba

###
PUT http://localhost:4000/api/trainer_pokemons/11ffc595-fed8-40f4-8cf1-f238edfae5ba
content-type: application/json

{
    "nickname": "Pi"
}

###
POST http://localhost:4000/api/trainers
content-type: application/json

{
    "name": "Oran",
    "password": "xyzpan"
}

###
POST http://localhost:4000/api/trainers/signin
content-type: application/json

{
    "id": "ee007900-d9a2-42ee-b165-e0d93e7f488f",
    "password": "xyzpan"
}

###
POST http://localhost:4000/api/trainer_pokemons
content-type: application/json

{
    "name": "scyther",
    "nickname": "buguim",
    "trainer_id": "74b48f26-ea47-4d3a-91ba-37dc5e67d8f3"
}

###
PUT http://localhost:4000/api/trainers/abb307bd-f4a6-4114-89e9-0cd849099d9c
content-type: application/json

{
    "name": "Novo Treinador",
    "password": "12345c"
}

