GET http://localhost:4000/api/trainers/271a8632-c9e7-41cd-9e82-8e3d91797509

###

GET http://localhost:4000/api/pokemons/pikach

###

DELETE http://localhost:4000/api/trainers/816a6a4a-e493-46e6-ae63-041fd8c97404

###
DELETE http://localhost:4000/api/trainer_pokemons/1340831e-54c1-4eb6-8a1f-7cd53050e5ec

###
GET http://localhost:4000/api/trainer_pokemons/11ffc595-fed8-40f4-8cf1-f238edfae5ba

###
PUT http://localhost:4000/api/trainer_pokemons/11ffc595-fed8-40f4-8cf1-f238edfae5ba
content-type: application/json

{
    "nickname": "Pi"
}

###
POST http://localhost:4000/api/trainers
content-type: application/json

{
    "name": "Oran",
    "password": "xyzpan"
}

###
POST http://localhost:4000/api/trainers/signin
content-type: application/json

{
    "id": "ee007900-d9a2-42ee-b165-e0d93e7f488f",
    "password": "xyzpan"
}

###
POST http://localhost:4000/api/trainer_pokemons
content-type: application/json

{
    "name": "scyther",
    "nickname": "buguim",
    "trainer_id": "74b48f26-ea47-4d3a-91ba-37dc5e67d8f3"
}

###
PUT http://localhost:4000/api/trainers/abb307bd-f4a6-4114-89e9-0cd849099d9c
content-type: application/json

{
    "name": "Novo Treinador",
    "password": "12345c"
}

