GET http://localhost:4000/api/trainers

###

GET http://localhost:4000/api/trainers

###
POST http://localhost:4000/api/trainers
content-type: application/json

{
    "name": "Treinador",
    "password": "123459"
}